### ISSUE TITLE
Missing DESCRIPTION file

### ISSUE THREAD

**Issue by Schamschula** [stk-kriging/stk#37]
As I was updating the MacPorts Portfile to version 2.8.0, the build failed, as

> the DESCRIPTION file /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_math_octave-stk/octave-stk/work/tmp-build could not be read: invalid stream object

This file was part of the 2.7.0 package.

**Comment by jbect** [comment]
@Schamschula thank you for reaching out.

I don't really understand what the problem is, could you be provide more detailed information?

**Comment by Schamschula** [comment]
I did a bit of additional testing.

1) a manual install from within octave works.
2) the MacPorts install of version 2.8.0 is broken, while version 2.7.0 correctly built and installed.

What has changed with the MacPorts Portfile?
Version 2.7.0 was pulled from SourceForge, while version 2.8.0 was pulled from GitHub. Sourcing from GitHub (even though it adds more complexity to the Portfile) shouldn't be an issue, as several other octave packages use the exact same mechanism and cleanly install.

Here is what is happening:
MacPorts uses the octave PortGroup to maintain (build, install, activate, deactivate and uninstall) octave packages.
See: https://github.com/macports/macports-ports/blob/master/_resources/port1.0/group/octave-1.0.tcl

It builds a package in several phases. In this case the failure happens when executing 

`try; pkg build -verbose -nodeps /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_math_octave-stk/octave-stk/work/tmp-build /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_math_octave-stk/octave-stk/work/stk-2.8.0.tar.gz; catch; disp(lasterror.message); exit(1); end_try_catch;`

within the `octave-cli` environment. This results in the above error message.

Note: I get the same error under arm64 (macOS Monterey) and x86_64 (macOS Ventura).

Here's the full log: [octave-stk-main.log](https://github.com/stk-kriging/stk/files/10368817/octave-stk-main.log)

**Comment by jbect** [comment]
@Schamschula I really don't know what the problem is, and I don't have access to a Mac.

As a first step, perhaps could you remove the try/catch around `pkg build` to get the location of the error?

**Comment by Schamschula** [comment]
Good idea!

I made a local version of the script w/o the try/catch code.

Here's what I get:

> Executing:  cd "/opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_math_octave-stk/octave-stk/work/stk" && /usr/bin/arch -arch $OCTAVE_ARCH /opt/local/bin/octave-cli -q -f -H --eval 'pkg build -verbose -nodeps /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_math_octave-stk/octave-stk/work/tmp-build /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_math_octave-stk/octave-stk/work/stk-2.8.0.tar.gz;' 
> warning: creating build directory /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_math_octave-stk/octave-stk/work/tmp-build
> warning: called from
>     build at line 49 column 5
>     pkg at line 737 column 7
> 
> error: the DESCRIPTION file /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_math_octave-stk/octave-stk/work/tmp-build could not be read: invalid stream object
> error: called from
>     get_description at line 36 column 5
>     build at line 69 column 10
>     pkg at line 737 column 7
>

**Comment by jbect** [comment]
Oh, I think I know: you are using the wrong tarball.

There two tarballs for each release, the one you need has the suffix `-octpkg.tar.gz`.

**Comment by Schamschula** [comment]
Bingo!

Many thanks!

**Comment by Schamschula** [comment]
I was actually using the source `.tar.gz` tarball.

We're up to date! https://github.com/macports/macports-ports/commit/a6112f3db50f8b17f8c8a5efebc2fafc7373eec1

**Comment by jbect** [comment]
Oh yes you're right, there even more than two tarballs on github :wink: 

I'm glad the problem is solved.
